cmake_minimum_required(VERSION 3.20)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/repo)

include(parse_args)
include(execute_workflow)
include(run_linters)
include(make_dependency_graph)
include(run_main)

set(binary_dir ${CMAKE_SOURCE_DIR}/build)
set(build_types Release Debug)
set(presets clang gcc)

function(main)
    parse_args()
    foreach(preset ${presets})
        foreach(build_typ ${build_types})
            execute_workflow(${build_typ} ${preset})
        endforeach()
    endforeach()
    make_dependency_graph_png()
    run_linters()
endfunction()

run_main()