cmake_minimum_required(VERSION 3.20)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/repo)

include(parse_args)
include(configure_build_test)
include(make_dependency_graph)
include(run_linters)
include(run_main)

function(main)
    parse_args()
    foreach(compiler clang++-15 g++)
        foreach(build_typ Release Debug)
            configure_build_test(${build_typ} ${compiler})
        endforeach()
    endforeach()
    make_dependency_graph_png()
    run_linters()
endfunction()

run_main()