include(shared)

function(execute_workflow build_typ preset)
    set(clang_tidy clang-tidy --quiet)
    set(ENV{KSAR_BUILD_DIR} ${build_typ}) # used in CMakePresets.json:configurePresets:base
    set(ENV{CMAKE_BUILD_TYPE} $ENV{KSAR_BUILD_DIR})
    if(NOT EXISTS ${binary_dir}/${preset}/$ENV{KSAR_BUILD_DIR})
        introduce(build/${preset}/${build_typ}:configure)
        execute_cmd(${CMAKE_COMMAND} --preset ${preset})
    endif()
    introduce(build/${preset}/${build_typ}:build)
    execute_cmd(${CMAKE_COMMAND} --build --preset ${preset})
    unset(ENV{KSAR_BUILD_DIR})
    unset(ENV{CMAKE_BUILD_TYPE})
endfunction()