include(shared)

function(make_dependency_graph_png)
    if(NOT EXISTS ${dependency_graph}.png)
        set(dependency_graph ${binary_dir}/dependency_graph)
        introduce(dependency_graph.png)
        execute_cmd(${CMAKE_COMMAND} -S ${CMAKE_SOURCE_DIR} -B ${binary_dir}/clang/Release/ --graphviz=${dependency_graph}.dot)
        execute_cmd(dot -Tpng ${dependency_graph}.dot -o ${dependency_graph}.png)
        file(GLOB graph_files ${dependency_graph}.dot.*)
        foreach(graph_file ${graph_files})
            file(REMOVE ${graph_file})
        endforeach()
    endif()
endfunction()