set(binary_dir ${CMAKE_SOURCE_DIR}/build/repo_cmake_script)

function(execute_cmd)
    execute_process(COMMAND ${ARGN} ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE)
endfunction()

function(introduce msg)
    string(TIMESTAMP timestamp %H:%M:%S)
    macro(set_show)
        set(show :::[${msg}]--------------${padding}${timestamp})
    endmacro()
    set_show()
    string(LENGTH ${show} len)
    math(EXPR n 80-${len})
    string(REPEAT "-" ${n} padding)
    set_show()
    message("\n${show}")
endfunction()